version: '3'

services:
  backend:
    build: backend/
    environment:
      - TZ=America/New_York
  mnemonic:
    build: mnemonic/
    environment:
      - TZ=America/New_York
  redis:
    image: redis
    restart: always
    environment:
      - TZ=America/New_York
  frontend:
    build: frontend/
    environment:
      - CHOKIDAR_USEPOLLING=true
      - TZ=America/New_York
  proxy:
    hostname: proxy
    build: proxy/
    ports:
      - 80:80
      - 443:443
    environment:
      - TZ=America/New_York
