version: '3'

services:
  backend:
    environment:
      FLASK_ENV: development
    volumes:
      - ./backend:/code
  frontend:
    volumes:
      - ./frontend:/app
      - /app/node_modules
  proxy:
    depends_on:
      - frontend
      - backend
      - mnemonic
    build:
      args:
        config: dev.conf
  mnemonic:
    environment:
      FLASK_ENV: development
    volumes:
      - ./mnemonic:/app
