<template>
<div>

<div class="level">
    <div class="level-left">
	<div class="title is-1">
	    Edit Import
	</div>
    </div>
    <div class="level-right">
	<div class="title is-3">
	    {{ numOrdersValid }} / {{ numOrdersEnabled }} ready
	</div>
    </div>
</div>

<div class="columns is-centered" v-if="orders.length == 0">
    <div class="column is-narrow">
	<div class="loadingio-spinner-dual-ring-1lfnptfc9d2"><div class="ldio-lwr9a5hdbq">
	<div></div><div><div></div></div>
	</div></div>
    </div>
</div>

<order v-for="order_id in orders" v-bind:order_id="order_id" :key="order_id">
</order>

<button class="button is-medium is-success" @click="run_import" :class="{ 'is-loading' : running_import }" v-bind:disabled="!ready"> Import </button>

<br />
<br />
<br />

</div>
</template>

<script>

import { getApi } from '../api';

import Order from '../components/Order.vue';

export default {
    data: function() {
	return {
	    running_import: false
	}
    },
    methods: {
	orderUpdated: function(value, index) {
	    this.$set(this.orders_valid, index, value);
	},
	run_import: async function() {
	    if(!this.ready)
		return;
	    let result = await getApi(`/import/${this.$route.params.id}/run`);
	    this.$router.push('/waitRun/' + this.$route.params.id);
	}
    },
    mounted: async function() {
	this.$store.dispatch('getImportAPI', { import_id : this.$route.params.id });
    },
    computed: {
	import_id: function() {
	    return this.$route.params.id;
	},
	orders: function() {
	    // Need to do this to make sure the import has been loaded
	    if(this.$store.state.imports[this.import_id])
		return this.$store.state.imports[this.import_id].orders;
	    else
		return [];
	},
	numOrdersValid: function() {
	    var total = 0;
	    for(var i = 0; i < this.orders.length; i++) {
		// Dereference order
		var order = this.$store.state.orders[this.orders[i]];
		if(!order || !order.enabled)
		    continue;
		var validAttr = order.salesrep_valid && order.customer_valid;
		var validItems = true;
		for(var j = 0; j < order.items.length; j++) {
		    var it = this.$store.state.items[order.items[j]];
		    if(it && !it.valid)
			validItems = false;
		}
		if(validItems && validAttr)
    		    total += 1;
	    }
	    return total;
	},
	numOrdersEnabled: function() {
	    var total = 0;
	    for(var i = 0; i < this.orders.length; i++) {
		if( this.$store.state.orders[this.orders[i]] &&
		    this.$store.state.orders[this.orders[i]].enabled)
		    total += 1;
	    }
	    return total;
	},
	ready: function() {
	    return this.numOrdersValid == this.numOrdersEnabled;
	}
    },
    components: {
	Order
    }

}
</script>

<style type="text/css">
@keyframes ldio-lwr9a5hdbq {
  0% { transform: rotate(0) }
  100% { transform: rotate(360deg) }
}
.ldio-lwr9a5hdbq div { box-sizing: border-box!important }
.ldio-lwr9a5hdbq > div {
  position: absolute;
  width: 104px;
  height: 104px;
  top: 48px;
  left: 48px;
  border-radius: 50%;
  border: 12px solid #000;
  border-color: #1d0e0b transparent #1d0e0b transparent;
  animation: ldio-lwr9a5hdbq 1.7241379310344827s linear infinite;
}
.ldio-lwr9a5hdbq > div:nth-child(2) { border-color: transparent }
.ldio-lwr9a5hdbq > div:nth-child(2) div {
  position: absolute;
  width: 100%;
  height: 100%;
  transform: rotate(45deg);
}
.ldio-lwr9a5hdbq > div:nth-child(2) div:before, .ldio-lwr9a5hdbq > div:nth-child(2) div:after { 
  content: "";
  display: block;
  position: absolute;
  width: 12px;
  height: 12px;
  top: -12px;
  left: 34px;
  background: #1d0e0b;
  border-radius: 50%;
  box-shadow: 0 92px 0 0 #1d0e0b;
}
.ldio-lwr9a5hdbq > div:nth-child(2) div:after { 
  left: -12px;
  top: 34px;
  box-shadow: 92px 0 0 0 #1d0e0b;
}
.loadingio-spinner-dual-ring-1lfnptfc9d2 {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-lwr9a5hdbq {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-lwr9a5hdbq div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>
